name = "bot-shield-api"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "your-analytics-kv-id"
preview_id = "your-analytics-kv-preview-id"

[[kv_namespaces]]
binding = "RULES_KV"
id = "your-rules-kv-id"
preview_id = "your-rules-kv-preview-id"

[[kv_namespaces]]
binding = "USERS_KV"
id = "your-users-kv-id"
preview_id = "your-users-kv-preview-id"

[env.development]
name = "bot-shield-api-dev"
vars = { ENVIRONMENT = "development" }

[env.production]
name = "bot-shield-api-prod"
vars = { ENVIRONMENT = "production" }